### ISSUE TITLE
Add compatibility for new command keys on NVDA 2022.4

### ISSUE THREAD

**Issue by CoBC** [CoBC/easyTableNavigator-1#12]
NVDA 2022.4 add several new table navigation commands:

> Added the following table commands. ([#14070](https://github.com/nvaccess/nvda/issues/14070))
> - Say all in column: NVDA+control+alt+downArrow
> - Say all in row: NVDA+control+alt+rightArrow
> - Read entire column: NVDA+control+alt+upArrow
> - Read entire row: NVDA+control+alt+leftArrow
easyTableNavigator should also introduce this new commands.

**Comment by CyrilleB79** [comment]
I have submitted #13 to fix this.
Actually, I had  already the code ready, but I was waiting for the merge of #11 to submit the pull request in order to avoid merge conflicts.
