### ISSUE TITLE
Table navigation layer cannot be activated in Word with UIA

### ISSUE THREAD

**Issue by CyrilleB79** [CoBC/easyTableNavigator-1#6]
### STR

* Go to Preferences -> Settings... -> Advanced panel and check "Use UI automation to access Microsoft Word document controls when available"
* Open a Word document containing a table or create it
* Set your caret in the first cell of the table
* Try to activate table navigation layer
* Try to navigate with arrows

### Expected result
The dedicated command should allow to activate table nav layer and you should be able to navigate cell by cell in the table.

### Actual result
When trying to activate table nav layer, this fail with the following message: "Not in a table"

### Context

* NVAccess is pushing to use UIA in recent versions of Word rather than object model because Microsoft does not intend to fix future bugs found in Office's object model. They have considered using UIA by default for recent versions of Word in 2019 and in 2021 but had to turn back due to unresolved bugs. Anyway, they will surely switch to UIA sooner or later.
* Some people already work with this option enabled, mostly for performence improvement in big documents.

Thanks!

**Comment by CyrilleB79** [comment]
March 2022 update:
UIA will be enabled by default in Word for recent versions of Office in NVDA 2022.1. Thus this issue will become more visible and its impact higher.

**Comment by CoBC** [comment]
Hmmmm, for now not idea on what can cause this issue. I'll try to 
investigate litle more later.

**Comment by LittleStar-VIP** [comment]
I have also experienced this problem.
